---
title: "US Coronavirus Cases"
author: "Micah Williams"
date: "3/29/2020"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(maptools)
library(janitor)
library(gganimate)
library(transformr)
library(geojsonio)
library(tidycensus)
library(gridExtra)
# census_api_key('f7c07c55451ec943fc1b438d589f8b068aeb43fc', install = T)
```

```{r import_data, message=FALSE, warning=FALSE}
today = Sys.Date()

date_num <- function(date){
  str_replace_all(as.character(date), '-', '')
}

w_filename <- function(name, path = 'plots/', filetype = 'png'){
  paste(path, date_num(Sys.Date()), '_', name, '.', filetype, sep = '')
}

get_cases <- function(tbl, cur_date){
  tbl %>%
    filter(date == cur_date) %>%
    pull(cases) %>%
    sum()
}

census <- rgdal::readOGR(dsn = './gz_2010_us_050_00_5m','gz_2010_us_050_00_5m')
corona <- read_csv('us-counties.csv', col_types = c('Dcccii')) %>%
  mutate(fips = if_else(county == 'New York City', "36061", fips)) %>% 
  group_by(fips) %>%
  arrange(date) %>%
  mutate(daily_infect_rate = map_if(date, 
                              ~length(cases[date == .+1]) == 1, 
                              ~(cases[date == .+1] - cases[date == .]) / cases[date == .], 
                              .else = NA_real_),
         state_code = map_chr(fips, ~str_extract(., '\\d{2}'))) %>%
  unnest(daily_infect_rate)

census.points <- fortify(census, region = 'GEO_ID')

census@data <- census@data %>%
  mutate(fips = paste(STATE,COUNTY,sep=''))%>%
  full_join(corona, by = c('fips', 'NAME' = 'county')) %>%
  clean_names()

covid <- census.points %>%
  full_join(census@data, by = c('id' = 'geo_id')) %>%
  mutate(cases = if_else(cases %in% c(0, NA), NA_integer_, cases))
  
states <- geojson_read(x = "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json", 
                 what = "sp")

# repair geometry... intersecting points
# (code from https://stackoverflow.com/questions/46003060/error-using-region-argument-when-fortifying-shapefile)
states <- rgeos::gBuffer(states, byid = T, width = 0)

state_lines <- fortify(states, region = 'id') %>%
  mutate(state = id) %>% select(-id)

county_lines <- census@data %>%
  select(c(geo_id:county,fips)) %>%
  full_join(census.points,  by = c('geo_id' = 'id')) %>%
  filter(!is.na(long), !is.na(lat))

state_fips_df <- census@data %>% 
  select(c(state, state_2)) %>% 
  unique() %>% 
  filter(!is.na(state), !is.na(state_2)) %>% 
  arrange(state)

state_fips <- state_fips_df %>%
  select(code = state) %>%
  mutate(code = as.character(code)) %>%
  t() %>%
  data.frame()

colnames(state_fips) <- make_clean_names(state_fips_df$state_2)

get_state_fips <- function(state){
  state_fips[state] %>% pull() %>% as.character()
}

rm(census, census.points, states)
```

```{r}
all_fips <- covid %>% pull(state) %>% unique() %>% as.character(.)
outside_fips <- c('15', '02','03','07','14','43','52', '72', NA)
mainland_fips <- all_fips[!all_fips %in% outside_fips & !is.na(all_fips)]

mainland_fips
```


```{r plot_states, fig.height = 9, fig.width = 12}
plot_states <- function(fips_codes, 
                        # limits.x = find_limits(x.outline)$sugg_long, 
                        # limits.y = find_limits(x.outline)$sugg_lat,
                        title = '',
                        setdate = today - 1,
                        outlines = county_lines){
  
  
  # join_by_cols <-  c("long", "lat", "order", "hole", "piece", "id" = "geo_id", "state", "county", "fips")
  
  x.data <- covid %>% filter(state %in% fips_codes, date == setdate)

  x.outline <- outlines %>% filter(state %in% fips_codes)
  
  ggplot(mapping = aes(long, lat, group = group)) +
    
    geom_path(color = '#bbbbbb',
              # size = 0.5,
              data = x.outline) +
    
    geom_polygon(aes(fill = cases),
                 # color = 'gray50',
                 data = x.data) +
    
    scale_fill_gradient(low = '#ddbbff', high = '#e01a1a', 
                        trans = 'log10', na.value = '#bbbbbb') +

    # scale_x_continuous(limits = limits.x) +
    # scale_y_continuous(limits = limits.y) +
    
    labs(title = paste(title,'Total Confirmed Coronavirus Cases by County'),
         subtitle = paste('Data from', format(x.data$date,'%B %d, %Y')),
         caption = 'Source: New York Times \nData for some counties missing. \nCreated by Micah Williams',
         fill = 'Cases', fips = 'County') +
    
    theme_void() +
    coord_equal() +
    theme(panel.grid = element_blank())
}

# plot_states(mainland_fips, setdate = '2020-04-06', outline= state_lines)
# ggsave(filename = 'plots/us/20200406_us.png', width = 12, height = 9)
```

```{r animate_states, fig.height = 9, fig.width = 12}
animate_states <- function(fips_codes, 
                        title = '',
                        outlines = county_lines){
  
  x.data <- covid %>% filter(state %in% fips_codes, !is.na(date))

  x.outline <- outlines %>% filter(state %in% fips_codes)
  
  new_animation <- ggplot(mapping = aes(long, lat, group = group)) +
    
    geom_path(color = '#bbbbbb',
              # size = 0.5,
              data = x.outline) +
    
    geom_polygon(aes(fill = cases),
                 # color = 'gray50',
                 data = x.data) +
    
    scale_fill_gradient(low = '#ddbbff', high = '#e01a1a', 
                        trans = 'log10', na.value = '#bbbbbb') +
    
    labs(title = paste(title,'Total Confirmed Coronavirus Cases by County'),
         subtitle = 'Date: {frame_time}',
         caption = 'Source: New York Times \n Data for some counties missing. \n Created by Micah Williams',
         fill = 'Cases', fips = 'County') +
    
    theme_void() +
    coord_equal() +
    theme(panel.grid = element_blank()) +
    transition_time(x.data$date)
  
  animate(new_animation, end_pause = 20, width = 8, height = 5, units = 'in', res = 144)
}

animate_states('15', title = 'Hawaii')
anim_save(filename = 'plots/hawaii.gif')
```

```{r hawaii}
plot_states('15', outlines = county_lines, setdate = '2020-04-06')

# ggsave(filename = 'plots/20200403_hi.png', width = 7, height = 5)
```

```{r}
tx <- covid %>%
  filter(state %in% c('48'))

tx_map_anim <- ggplot(tx_all_counties, aes(long, lat, group = group, fill = cases)) +
  geom_polygon() +
  geom_path(alpha = 0.3) +
  scale_fill_gradient(low = '#ffeeee', high = '#f00000', 
                      na.value = '#dddddd', trans = 'log10') +
  # scale_y_continuous(limits = c(34.9, 36.7)) +
  # scale_x_continuous(limits = c(-90.5, -81.5)) +
  labs(title = 'Total Confirmed Coronavirus Cases by County in Texas',
       subtitle = 'Date: {closest_state}',
       caption = 'Source: New York Times \n Data for some counties missing.',
       x = 'longitude', y = 'latitude',
       fill = 'Cases', fips = 'County') +
  coord_equal() +
  theme_minimal() #+
  transition_states(states = date)

# animate(tx_map_anim, end_pause = 20, width = 7, height = 5, units = 'in', res = 72)  

# anim_save(filename = 'plots/tx_anim.gif', fig.height = 5, fig.width = 7)
```

```{r}
tx_geom <- tx %>%
  filter(date == today) %>%
  .[,c(1:7, 12:17)] %>%
  unique()

dates <- tx %>% filter(!is.na(date)) %>% pull(date) %>% unique()
# all_tx_counties <- 
  
tx_all_counties <- tibble(date = dates,
  date_rep = map(dates, ~tx_geom)) %>%
  unnest(date_rep) %>%
  full_join(tx, by = c(names(tx_geom), 'date'))

glimpse(tx_all_counties)
```

```{r, fig.height=5, fig.width = 7}
ca <- census@data %>% 
  filter(!is.na(date)) %>%
  full_join(census.points, by = c('geo_id' = 'id')) %>%
  filter(state == '06')


cali_geom <- states.points %>% filter(id == '06')
  
ca_map_anim <- ggplot(ca, aes(long, lat, group = group, fill = cases)) +
  geom_polygon() +
  geom_path(alpha = 0.3) +
  geom_path(data = cali_geom, aes(long, lat, group = group, fill = NULL)) +
  scale_fill_gradient(low = '#eeeeff', high = '#f00000', 
                      na.value = '#dddddd', trans = 'log10') +
  labs(title = 'Total Confirmed Coronavirus Cases by County in California',
       subtitle = 'Date: {frame_time}',
       caption = 'Source: New York Times',
       x = 'longitude', y = 'latitude',
       fill = 'Cases', fips = 'County') +
  coord_equal() +
  theme_minimal() +
  transition_time(date)

animate(ca_map_anim, end_pause = 20, width = 7, height = 5, units = 'in', res = 144)

ggsave(filename = 'plots/april03_ca.png', width = 7, height = 5, units = 'in', res = 288)
anim_save(filename = 'plots/20200404_ca.gif', animation = ca_map_anim,
          width = 7, height = 5, units = 'in', res = 288, end_pause = 10)

```

```{r}
corona %>% 
  filter(fips %in% c('06037', '53033', '15003')) %>% 
  ggplot(aes(date, cases, color = fips)) + 
  geom_line(size = 1.1) +
  geom_point() +
  scale_color_discrete(name = 'County',
                       labels = c('Los Angeles County',
                                  'Honolulu County',
                                  'King County (Seattle)')) +
  labs(title = 'Confirmed Coronavirus Cases',
       subtitle = 'Data as of April 3',
       caption = 'Source: New York Times') +
  theme_minimal() +
  theme(legend.position = 'bottom') +
  transition_reveal(along = date)

anim_save(filename = 'plots/20200403_counties.gif', fig.height = 5, fig.width = 7, end_pause = 10)
```

```{r california}
ca_anim <- animate_states('06', title = 'California')

anim_save('plots/ca.gif', height = 6, width = 8)
```


```{r texas, fig.width = 5, fig.height = 9}
tx_county_pops <- get_acs(geography = 'county',
                          variables = 'B01003_001E', 
                          state = get_state_fips('texas')) %>%
  select(c(fips = GEOID, pop = estimate))

tx <- corona %>% filter(state_code == get_state_fips('texas')) %>%
  left_join(tx_county_pops, by = c('fips')) %>%
  mutate(cases_per_1000 = cases / pop * 1000)

tx_summary <- tx %>%
  group_by(date) %>%
  summarize(total_cases = sum(cases),
            cases_per_1000 = total_cases / sum(tx_county_pops$pop) * 1000)

tx_counties_anim <- tx %>%
  ggplot(aes(date,cases_per_1000, color = county)) +
  geom_line(alpha = 0.25, size = 0.8) +
  geom_line(data = tx_summary, color = 'steelblue',
            alpha = 1, size = 1.5) +
  labs(y = 'Cases per 1,000 People') +
  theme(legend.position = 'none')

grid.arrange(
tx_counties_anim + labs(title = 'Confirmed Coronavirus Cases per 1,000 people in Texas, by County',
                        subtitle = 'Linear scale', x = '')+
  annotate('text', x = as.Date('2020-02-22'), y = 0.15,
           label = 'Texas (total)',
           size = 4, hjust = 0),
tx_counties_anim + 
  scale_y_log10(breaks = 1*10^c(-4:0),
                labels = format(1*10^c(-4:0), 
                                scientific = T)) +
  theme(axis.text.y = element_text(angle = 35)) +
  labs(subtitle = 'Logarithmic scale',
       caption = 'Source: New York Times, US Census\n Created by Micah Williams'),
nrow = 2)

ggsave(filename = 'plots/texas_infectionrates.png', height = 9, width = 5)

  #+
  # transition_reveal(date)


tx %>% filter(date == '2020-03-25') %>% arrange(desc(cases_per_1000))

plot_states
```

```{r}
plot_states("42", title = 'Pennsylania')

animate_states("42", "Pennsylvania")
anim_save(filename = 'plots/PA_0.5fps_nowidth.gif', 
          width = 8, height = 4, fps = 0.5)
```

```{r top_ten}
top_ten <- corona %>% filter(fips %in%  top_ten_fips, date >= '2020-03-07')

top_ten_order <- top_ten %>% filter(date =='2020-04-07') %>% arrange(desc(cases)) %>% pull(county)

top_ten$county <- factor(top_ten$county, top_ten_order, ordered = T)

line_plot <- top_ten %>% 
  ggplot(aes(date, cases, color = county)) +
  geom_line(size = 1.2) +
  labs(y = 'Total Confirmed Cases (thousands)', x = 'Date',
       title = 'Confirmed Cases of Coronavirus, Top 10 Counties in US',
       subtitle = 'Date: {frame_along}', color = 'County',
       caption = 'Source: New York Times \n Created by Micah Williams') +
  scale_color_brewer(type = 'qual', palette = 'Paired') +
  theme_minimal() +
  scale_y_continuous(breaks = seq(0,80000,20000), 
                     labels = seq(0,80,20)) +
    theme(legend.position = c(0.15, 0.55),
          legend.background = element_rect(fill = '#ffffff90', color = '#ffffffa0')) +
  transition_reveal(date)

line_anim <- animate(line_plot, end_pause = 20, width = 7, height = 5, units = 'in', res = 144)
```

```{r infection_rate}
three_day <- corona %>% filter(date >= '2020-04-03', cases > 8) %>%
  group_by(fips) %>%
  mutate(avg_new_infect_3day = mean(daily_infect_rate)) %>%
  filter(date == '2020-04-06', avg_new_infect_3day >= 0) %>%
  ungroup() %>% 
  mutate(sig_score = avg_new_infect_3day*(log10(cases)),
         sig_normalized = percent_rank(sig_score)) 

three_day %>%
  ggplot(aes(cases, avg_new_infect_3day)) +
  geom_point(color = if_else(three_day$sig_normalized > 0.97, '#d01a1a', '#000000'),
             alpha = if_else(three_day$sig_normalized > 0.97, 1, 0.3)) +
  scale_x_log10(breaks = 1*10^c(1:4),
                labels = c('10','100','1,000','10,000')) +
  labs(x = ' Total Cases', y = 'Daily New Infection Rate',
       title = 'Confirmed Cases vs. Average Daily Infection Rate',
       subtitle = 'Infection rate calculated as average daily rate of change in infections from April 3-6',
       caption = 'Source: New York Times\n Created by Micah Williams') +
  theme_minimal()

ggsave('plots/avg_change.png', width = 7, height = 5)

three_day %>% 
  filter(date == '2020-04-06',
         sig_normalized > 0.97) %>%
  select(-c(date, daily_infect_rate, state_code)) %>%
  arrange(desc(sig_normalized)) %>%
  group_by(state) %>%
  count() %>%
  arrange(desc(n)) %>% 
  paste()
```

```{r death_rate}
corona %>% 
  filter(date == max(date),
         deaths > 0,
         cases > 20) %>%
  ggplot(aes(cases,deaths)) +
  geom_jitter(height = 0.1) +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = 'lm')
```


